# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elif_test_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_companies', to='elif_test_job.Company'),
        ),
    ]
