# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elif_test_job', '0002_auto_20170718_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_companies', to='elif_test_job.Company'),
        ),
    ]
